- id: esstischlampe_ein
  alias: Esstischlampe ein
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: NAA0003539
      channel: 1
      param: PRESS_SHORT
  action:
    service: switch.turn_on
    entity_id: switch.Esstischlampe
- id: esstischlampe_aus
  alias: Esstischlampe aus
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: NAA0003539
      channel: 2
      param: PRESS_SHORT
  action:
    service: switch.turn_off
    entity_id: switch.Esstischlampe
- id: wohnzimmerlampe_ein
  alias: Wohnzimmerlicht ein
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: NAA0003539
      channel: 1
      param: PRESS_LONG
  action:
    service: homeassistant.turn_on
    entity_id: group.Wohnzimmerlicht
- id: wohnzimmerlampe_aus
  alias: Wohnzimmerlicht aus
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: NAA0003539
      channel: 2
      param: PRESS_LONG
  action:
    service: homeassistant.turn_off
    entity_id: group.Wohnzimmerlicht
- id: wohnzimmerlampe_ein_1
  alias: Wohnzimmerlampe ein
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: NEQ1001598
      channel: 1
      param: PRESS_SHORT
  action:
    service: switch.turn_on
    entity_id: switch.Wohnzimmerlampe
- id: wohnzimmerlampe_aus_1
  alias: Wohnzimmerlampe aus
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: NEQ1001598
      channel: 2
      param: PRESS_SHORT
  action:
    service: switch.turn_off
    entity_id: switch.Wohnzimmerlampe
- id: couch_ein
  alias: Couch ein
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: NEQ1001598
      channel: 3
      param: PRESS_SHORT
  action:
    service: switch.turn_on
    entity_id: switch.Couch
- id: couch_aus
  alias: Couch aus
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: NEQ1001598
      channel: 4
      param: PRESS_SHORT
  action:
    service: switch.turn_off
    entity_id: switch.Couch
- id: tv_ambiente_ein
  alias: TV Ambiente ein
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: NEQ1001598
      channel: 5
      param: PRESS_SHORT
  action:
    service: switch.turn_on
    entity_id: switch.Kleine_Lampe
- id: tv_ambiente_aus
  alias: TV Ambiente aus
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: NEQ1001598
      channel: 6
      param: PRESS_SHORT
  action:
    service: switch.turn_off
    entity_id: switch.Kleine_Lampe
- id: schlafzimmer_ein
  alias: Schlafzimmer Ein
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: NAA0004604
      channel: 1
      param: PRESS_SHORT
  action:
    service: light.turn_on
    entity_id: light.bedroom
- id: schlafzimmer_aus
  alias: Schlafzimmer Aus
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: NAA0004604
      channel: 2
      param: PRESS_SHORT
  action:
    service: light.turn_off
    entity_id: light.bedroom
- id: "k\xFCche_ein"
  alias: "K\xFCche Ein"
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: OEQ0484327
      channel: 1
      param: PRESS_SHORT
  action:
    service: switch.turn_on
    entity_id: switch.kitchen_light
- id: "k\xFCche_aus"
  alias: "K\xFCche Aus"
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: OEQ0484327
      channel: 2
      param: PRESS_SHORT
  action:
    service: switch.turn_off
    entity_id: switch.kitchen_light
- id: vorraum_ein
  alias: Vorraum Ein
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: OEQ0484300
      channel: 1
      param: PRESS_SHORT
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: OEQ0484359
      channel: 1
      param: PRESS_SHORT
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: OEQ0484358
      channel: 1
      param: PRESS_SHORT
  action:
    service: homeassistant.turn_on
    entity_id: group.vorraumdeckenlampen
- id: vorraum_aus
  alias: Vorraum Aus
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: OEQ0484300
      channel: 2
      param: PRESS_SHORT
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: OEQ0484359
      channel: 2
      param: PRESS_SHORT
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: OEQ0484358
      channel: 2
      param: PRESS_SHORT
  action:
    service: homeassistant.turn_off
    entity_id: group.vorraumdeckenlampen
- id: leave_home
  alias: Leave Home
  hide_entity: true
  trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: OEQ0484300
      channel: 2
      param: PRESS_LONG
  action:
    service: script.turn_on
    entity_id: script.leave_home
- id: radio_volume
  alias: Set Radio Volume
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_slider.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: "{% if is_state(\"input_select.chromecast_radio\", \"Badezimmer\"\
        ) %} media_player.bad_cast {% elif is_state(\"input_select.chromecast_radio\"\
        , \"Wohnzimmer\") %} media_player.wohnzimmercast {% elif is_state(\"input_select.chromecast_radio\"\
        , \"\xDCberall\") %} media_player.alles {% endif %}\n"
      volume_level: '{{  states.input_slider.volume_radio.state  }}'
- action:
  - data:
      message: "Wohnzimmer l\xFCften!"
      title: Im Wohnzimmer hat es {{  states.sensor.livingroom_humidity.state  }}%
        Luftfeuchtigkeit
    service: notify.notify_group
  alias: Luften
  condition:
  - after: 08:00
    before: '22:30'
    condition: time
  - condition: state
    entity_id: binary_sensor.should_vent
    state: 'on'
  id: '1505935066796'
  trigger:
  - entity_id: binary_sensor.livingroom_humidity_too_high
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: Luftfeuchtigkeit ist wieder unter 60%
      title: "Genug gel\xFCftet"
    service: notify.notify_all
  alias: LuftenBeenden
  condition: []
  id: '1505936730583'
  trigger:
  - entity_id: sensor.livingroom_humidity_too_high
    from: 'on'
    platform: state
    to: 'off'
