- alias: 'L체ften notwending'
  trigger:
    platform: numeric_state
    entity_id: sensor.esp_livingroom_humidity
    value_template: '{{ states.sensor.esp_livingroom_humidity.state }}'
    above: 60.00
  action:
    service: notify.pushbullet
    data_template:
      title: "Wohnzimmer l체ften!"
      message: "Die Luftfeuchtigkeit betr채gt {{ states.sensor.esp_livingroom_humidity.state }}%, bitte l체ften!"
